server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test666?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672

my:
  context:
    enable: true
    content: content
    context: context
debug: false
logging:
  level:
    com.cdt.cache.mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
---
# cache
